### ISSUE TITLE
Custom øvelser med link

### ISSUE THREAD

**Issue by Hestikka** [kasperdyrvig/parloer#24]
I modul 3 er de skriftlige øvelser ikke i parlør-appen, men på https://learngreenlandic.com/online/. Så jeg har brug for at kunne lave en custom felt med link. Så samme opbygning som de mundtlige øvelser, men med link.

**Comment by kasperdyrvig** [comment]
Måden at lave en ekstern øvelse:

```
---
tags: homework
partOfLesson: 17
previewText: Lav øvelsen
linkText: Åbn øvelsen
externalLink: https://...
---
```
